// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB-qEXYoN-pFHklUDFAn1LFpxszgh58Gs',
    appId: '1:892468549619:web:3595c0827655847ca72486',
    messagingSenderId: '892468549619',
    projectId: 'knucklebones-9bfd6',
    authDomain: 'knucklebones-9bfd6.firebaseapp.com',
    databaseURL: 'https://knucklebones-9bfd6-default-rtdb.firebaseio.com',
    storageBucket: 'knucklebones-9bfd6.appspot.com',
    measurementId: 'G-Z3NF0PV6PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlKC0UgPXhJJiQOQrNyS0e6bzZRvBKpZE',
    appId: '1:892468549619:android:59f5543b7aba74c7a72486',
    messagingSenderId: '892468549619',
    projectId: 'knucklebones-9bfd6',
    databaseURL: 'https://knucklebones-9bfd6-default-rtdb.firebaseio.com',
    storageBucket: 'knucklebones-9bfd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBofJQDOzHMz__ubYQIY5p1rNsHxoKO4MQ',
    appId: '1:892468549619:ios:8f5f1eb0a473e12ba72486',
    messagingSenderId: '892468549619',
    projectId: 'knucklebones-9bfd6',
    databaseURL: 'https://knucklebones-9bfd6-default-rtdb.firebaseio.com',
    storageBucket: 'knucklebones-9bfd6.appspot.com',
    iosClientId: '892468549619-so7c59qvm6mp9jg2uq8s8oe8r8463qs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.knucklebones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBofJQDOzHMz__ubYQIY5p1rNsHxoKO4MQ',
    appId: '1:892468549619:ios:8f5f1eb0a473e12ba72486',
    messagingSenderId: '892468549619',
    projectId: 'knucklebones-9bfd6',
    databaseURL: 'https://knucklebones-9bfd6-default-rtdb.firebaseio.com',
    storageBucket: 'knucklebones-9bfd6.appspot.com',
    iosClientId: '892468549619-so7c59qvm6mp9jg2uq8s8oe8r8463qs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.knucklebones',
  );
}
